application: miasalute
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /_ah/login_required
  script: do_openid_login.py

#- url: /ClientLogin
#  script: ClientLogin.py

- url: /.*
  script: appengine_main.py
  #login: required
  secure: always
